tests:
  services:
    - postgres:9.5
  script:
    - git clone git@git.seclab.cs.ucsb.edu:cgc/farnsworth
    - pip install --process-dependency-links -U ./farnsworth
    - pip install -U -e .
    - farnsworth/setupdb.sh .env.test
    - nosetests tests
  tags: ["angr"]

# lint:
#   script:
#     - lint.py
#   tags: ["cgc-linter"]

docs:
  script: "generate_docs"
  tags: ["cgc-linter"]

build_images:
  only: ["master"]
  stage: deploy
  script:
  - cgc-build scriba
  tags: ["docker-builder"]
